# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'HowTaxingRelease' do
  config = use_native_modules!
  # ChannelIO SDK와 react-native-channel-plugin 추가
  pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/latest/xcframework.podspec'
#   pod 'RNChannelIO', :path => '../node_modules/react-native-channel-plugin'
#   pod 'ChannelIOSDK', '~> 10.3.1'
pod 'RNChannelIO', :path => '../node_modules/react-native-channel-plugin'
# pod 'ChannelIOSDK', '12.4.1'

#  pod 'NMapsMap', '~> 3.20.0'
 pod 'RNSVG', :path => '../node_modules/react-native-svg'
 pod 'KakaoSDK', '~> 2.0'
#  pod 'NaverThirdPartyLogin', :path => '../node_modules/@react-native-seoul/naver-login'

  # pod 'GoogleSignIn', '7.0.0'
  use_react_native!(
    :path => config[:reactNativePath],
                    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HowTaxingReleaseTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if ['hermes', 'ChannelIOSDK','RNChannelIO', 'NaverThirdPartyLogin'].include?(target.name)
        target.build_phases.each do |phase|
          if phase.respond_to?(:name) && phase.name == '[CP] Embed Pods Frameworks'
            target.build_phases.delete(phase)
          end
        end
      end
    end

    # React Native 기본 설정
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
