source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

prepare_react_native_project!

use_frameworks! :linkage => :dynamic

target 'HowTaxingRelease' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false, # Hermes 활성화
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
# pod 'KakaoOpenSDK',https://devrepo.kakao.com/nexus/content/groups/public/com/kakao/sdk/KakaoOpenSDK/1.21.1/KakaoOpenSDK-1.21.1.zip'

  pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/latest/xcframework.podspec'
  pod 'RNChannelIO', :path => '../node_modules/react-native-channel-plugin'
  pod 'NMapsMap', '~> 3.20.0'
pod 'RNSVG', :path => '../node_modules/react-native-svg'
pod 'KakaoSDK', '~> 2.0'
pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
pod 'Alamofire', '~> 5.7'


  target 'HowTaxingReleaseTests' do
    inherit! :complete
  end

  post_install do |installer|
      react_native_post_install(installer)

      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end
    end
end
